name: Deploy
on:
  push:
    branches:
      - "main"
jobs:
  deploy: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./key.pem && chmod 0600 ./key.pem
      - uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATOCMS_API_TOKEN: ${{ secrets.DATOCMS_API_TOKEN }}
          envkey_RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
          envkey_TEBEX_STORE_SECRET: ${{ secrets.TEBEX_STORE_SECRET }}
          file_name: .env
          fail_on_empty: false
      - run: mkdir -p ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - run: scp -i ./key.pem -P 3276 ./.env www@37.77.106.193:~/app/source/.env
      - run: npm install -g pm2
      - run: pm2 deploy production